-- Auto-generated by scripts/generate-category-seed-sql.mjs
-- Generated from manifest: 2026-07-18T17:09:15.405Z

update public.categories set active = false
where id in ('cat-nature', 'cat-people', 'cat-animals', 'cat-architecture');

insert into public.categories (id, name, description, icon, sort_order, active) values
  ('cat-world-cup', 'World Cup', 'Global football fever — real match photos vs AI-generated tournament scenes.', '⚽', 1, true),
  ('cat-lebron-decision', 'LeBron / The Decision', 'NBA icon energy and ESPN press-conference vibes — spot the synthetic hoop dreams.', '🏀', 2, true),
  ('cat-brain-rot', 'Brain Rot', 'Chronically online aesthetics — meme-tier visuals vs uncanny AI slop.', '🧠', 3, true),
  ('cat-nyc-core', 'NYC Core', 'Subway tiles, fire escapes, bodega cats — authentic NYC or AI city-core cosplay?', '🗽', 4, true),
  ('cat-food', 'Food', 'Plated perfection and greasy glory — can you taste the difference in the pixels?', '🍕', 5, true)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  active = excluded.active;

